### ISSUE TITLE
Link to past rebates 

### ISSUE THREAD

**Issue by AdithyaKrishnaK** [DevCom-IITB/mess-i-dashboard#20]
In some hostels, there are systems which allow a person to be on rebate for less than a specified period. Hall mangers would have to find the person and manually check their history to check this condition right now. A link to rebate history which shows accepted rebates need to be shown to the hall mangers in the interface to accept a rebate request.

**Comment by DheGit** [comment]
Implemented as an option on the pending rebate cards.
