### ISSUE TITLE
Redirect people with admin access from student rebate section

### ISSUE THREAD

**Issue by kumarrahul33** [DevCom-IITB/mess-i-dashboard#25]
Currently, a person with admin access(like an admin or hall manager) can go to the /dashboard/rebates URL and get an empty page. Many Students have this URL bookmarked for rebates(applying and seeing their rebates). Since an admin does not apply for a rebate, he/she should not have access to this page. This might create confusion.

**Comment by kumar-09** [comment]
Issue resolved
